ALTER TABLE calls_sessions ADD COLUMN IF NOT EXISTS issipparticipant boolean DEFAULT FALSE;
ALTER TABLE calls_sessions ADD COLUMN IF NOT EXISTS confirmedat bigint NOT NULL DEFAULT 0;
ALTER TABLE calls_sessions ADD COLUMN IF NOT EXISTS sid VARCHAR(64) NOT NULL DEFAULT '';
ALTER TABLE calls_sessions ADD COLUMN IF NOT EXISTS authsessionid VARCHAR(26) NOT NULL DEFAULT '';
