version: "2"
run:
  modules-download-mode: readonly

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
  exclusions:
    generated: lax
    paths:
      - webapp
      - standalone
      - lt

linters:
  default: none
  enable:
    - copyloopvar     # Checks for pointers to enclosing loop variables
    - errcheck        # Detects unchecked errors
    - govet           # Examines Go source code and reports suspicious constructs
    - ineffassign     # Detects when assignments to existing variables are not used
    - makezero        # Finds slice declarations with non-zero initial length
    - misspell        # Finds commonly misspelled English words
    - revive          # Drop-in replacement of golint
    - staticcheck     # Set of rules from staticcheck
    - unconvert       # Removes unnecessary type conversions
    - unused          # Checks Go code for unused constants, variables, functions and types
    - whitespace      # Checks for unnecessary newlines at the start and end of functions
  settings:
    govet:
      disable:
        - fieldalignment
        - shadow
      enable-all: true
  exclusions:
    generated: lax
    paths:
      - webapp
      - standalone
      - lt

