quiet: False
with-expecter: true
dir: "server/mocks/{{.PackagePath}}"
packages:
    github.com/mattermost/mattermost-plugin-calls/server/interfaces:
        config:
        interfaces:
            Metrics:
            Store:
            RTCDClient:
    github.com/mattermost/mattermost/server/public/plugin:
        config:
        interfaces:
            API:
    github.com/mattermost/mattermost/server/public/shared/mlog:
        config:
        interfaces:
            LoggerIFace:
    github.com/mattermost/rtcd/service/rtc:
        config:
        interfaces:
            Metrics:
