// This file is automatically generated. Do not modify it manually.

package main

import (
	"encoding/json"

	"github.com/mattermost/mattermost-server/v6/model"
)

var manifest model.Manifest

const manifestStr = `
{
  "id": "com.mattermost.calls",
  "name": "Calls",
  "description": "Integrates real-time voice communication in Mattermost",
  "version": "0.1.0",
  "min_server_version": "6.0.0",
  "server": {
    "executables": {
      "darwin-amd64": "server/dist/plugin-darwin-amd64",
      "linux-amd64": "server/dist/plugin-linux-amd64"
    },
    "executable": ""
  },
  "webapp": {
    "bundle_path": "webapp/dist/main.js"
  },
  "settings_schema": {
    "header": "",
    "footer": "",
    "settings": [
      {
        "key": "UDPServerPort",
        "display_name": "RTC Server Port",
        "type": "number",
        "help_text": "The UDP port the RTC server will listen on.",
        "placeholder": "",
        "default": "8443"
      },
      {
        "key": "AllowEnableCalls",
        "display_name": "Allow Enable Calls",
        "type": "bool",
        "help_text": "When set to true, it allows channel admins to enable calls in their channels. It also allows participants of DMs/GMs to enable calls.",
        "placeholder": "",
        "default": false
      }
    ]
  }
}
`

func init() {
	if err := json.Unmarshal([]byte(manifestStr), &manifest); err != nil {
		panic(err.Error())
	}
}
