// This file is automatically generated. Do not modify it manually.

package main

import (
	"encoding/json"

	"github.com/mattermost/mattermost-server/v6/model"
)

var manifest model.Manifest

const manifestStr = `
{
  "id": "com.mattermost.talk",
  "name": "Talk",
  "description": "Integrates real-time voice communication in Mattermost",
  "version": "0.3.0",
  "min_server_version": "6.0.0",
  "server": {
    "executables": {
      "linux-amd64": "server/dist/plugin-linux-amd64"
    },
    "executable": ""
  },
  "webapp": {
    "bundle_path": "webapp/dist/main.js"
  },
  "settings_schema": {
    "header": "",
    "footer": "",
    "settings": []
  }
}
`

func init() {
	if err := json.Unmarshal([]byte(manifestStr), &manifest); err != nil {
		panic(err.Error())
	}
}
