---
title: "Mattermost Calls"
copyright: "©2015-present Mattermost,Inc. All Rights Reserved. See LICENSE for license information."
description: "This document includes a list of open source components used in Mattermost Calls plugin, including those that have been modified."
search:
  - "go.mod"
  - "build/go.mod"
  - "server/public/go.mod"
  - "standalone/package.json"
  - "webapp/package.json"
dependencies: []
devDependencies: []
