name: cd
on:
  workflow_run:
    workflows: ["ci"]
    types:
      - completed
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: read

jobs:
  plugin-cd:
    secrets: inherit
    env:
      RUDDER_DATAPLANE_URL: ${{ secrets.MM_RUDDER_DATAPLANE_URL }}
      RUDDER_WRITE_KEY: ${{ secrets.MM_RUDDER_CALLS_PROD }}
    uses: mattermost/actions-workflows/.github/workflows/plugin-cd.yml@main
